version: "3.9"

services:
  frontend:
    build: ./blog
    ports:
      - "3000:3000"
    volumes:
      - ./blog:/app
    networks:
      - app-network

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./blog/public/md:/app/public/md
    ports:
      - "5000:5000"
    command: python server.py
    networks:
      - app-network

  db:
    build: ./db
    volumes:
      - ./db/data:/var/lib/mysql
    env_file: db.development.env
    ports:
      - "${DB_PORT}:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
