version: "3.9"

services:
  frontend:
    build: ./blog
    ports:
      - "3000:3000"
    volumes:
      - ./blog:/app

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./blog/public/md:/app/public/md
    ports:
      - "5000:5000"
    command: python server.py